CREATE TABLE [dbo].[OrdersBillingEntriesTable](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[billingEntryId] [NVARCHAR](MAX) NULL,
	[occurredAt] [DATETIME] NOT NULL,
	[typeId] [NVARCHAR](MAX) NULL,
	[typeName] [NVARCHAR](MAX) NULL,
	[offerId] [NVARCHAR](MAX) NULL,
	[offerName] [NVARCHAR](MAX) NULL,
	[amount] [DECIMAL](18, 2) NOT NULL,
	[currency] [NVARCHAR](MAX) NULL,
	[orderId] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_dbo.OrdersBillingEntriesTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[OfferTable](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[offerId] [NVARCHAR](MAX) NULL,
	[name] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_dbo.OfferTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[OfferBillingEntriesTable](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[offerId] [NVARCHAR](MAX) NULL,
	[price] [DECIMAL](18, 2) NOT NULL,
	[Name] [NVARCHAR](MAX) NULL,
	[quantity] [INT] NOT NULL,
 CONSTRAINT [PK_dbo.OfferBillingEntriesTable] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[OfferBillingEntriesTable] ADD  DEFAULT ((0)) FOR [quantity]
GO

CREATE TABLE [dbo].[OrderTable](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[orderId] [varchar](45) NOT NULL,
	[erpOrderId] [int] NULL,
	[invoiceId] [int]  NULL,
	[storeId] [int]

 CONSTRAINT [PK_panel_lista] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [si] UNIQUE NONCLUSTERED 
(
	[orderId] ASC,
	[storeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO